# --- 1. XÁC THỰC VÀ PHÂN QUYỀN (APPLICATION LAYER) ---
allow_anonymous false
password_file D:/mqtt-defense-lab/configs/passwordfile
acl_file D:/mqtt-defense-lab/configs/aclfile

# --- 2. MÃ HÓA ĐƯỜNG TRUYỀN (TRANSPORT LAYER - TLS) ---
listener 8883
cafile D:/mqtt-defense-lab/configs/ca.crt
certfile D:/mqtt-defense-lab/configs/server.crt
keyfile D:/mqtt-defense-lab/configs/server.key